// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "In England",
                            Name = "London"
                        },
                        new
                        {
                            Id = 2,
                            Description = "In Spain",
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 3,
                            Description = "In Germany",
                            Name = "Munich"
                        },
                        new
                        {
                            Id = 4,
                            Description = "In France",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 5,
                            Description = "In Italy",
                            Name = "Milan"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A treasure trove of art and antiquities from around the world.",
                            Name = "The British Museum"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "The official residence of the British monarch.",
                            Name = "Buckingham Palace"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "One of the world's greatest art galleries, featuring European art from the 12th to early 20th century.",
                            Name = "Prado Museum"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Home to Real Madrid, one of the world's most famous football clubs.",
                            Name = "Santiago Bernabéu Stadium"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "A fairy-tale castle in the Bavarian Alps.",
                            Name = "Neuschwanstein Castle"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "The world's largest beer festival, held annually.",
                            Name = "Oktoberfest"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            Description = "The iconic iron tower, a symbol of Paris.",
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 4,
                            Description = "A masterpiece of French Gothic architecture.",
                            Name = "Notre-Dame Cathedral"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 5,
                            Description = "One of the largest cathedrals in the world, known for its intricate Gothic architecture.",
                            Name = "Duomo di Milano"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 5,
                            Description = "One of the world's most famous opera houses.",
                            Name = "La Scala Opera House"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
